# Generated by Django 5.2.10 on 2026-01-28 18:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='lease_end',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='lease_start',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='passport_copy',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='unit',
        ),
        migrations.AddField(
            model_name='tenant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenant',
            name='ejari_number',
            field=models.CharField(blank=True, help_text='Official Dubai Contract ID', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='passport_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_profile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tenant',
            name='emirates_id',
            field=models.CharField(default=0, help_text='UAE ID Number', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tenant',
            name='phone',
            field=models.CharField(max_length=50),
        ),
    ]
