# Generated by Django 5.2.10 on 2026-01-31 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_remove_tenant_lease_end_remove_tenant_lease_start_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='user',
        ),
        migrations.AlterField(
            model_name='tenant',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='emirates_id',
            field=models.CharField(blank=True, help_text='UAE ID Number', max_length=50, null=True),
        ),
    ]
