# Generated by Django 5.2.10 on 2026-02-01 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_remove_unit_is_occupied_property_description_and_more'),
        ('tenants', '0003_remove_tenant_user_alter_tenant_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='ejari_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='emirates_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_frequency', models.CharField(choices=[('1_CHEQUE', '1 Cheque'), ('4_CHEQUES', '4 Cheques'), ('12_CHEQUES', '12 Cheques')], default='4_CHEQUES', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('contract_file', models.FileField(blank=True, null=True, upload_to='leases/contracts/')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='tenants.tenant')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='properties.unit')),
            ],
        ),
    ]
