# Generated by Django 5.2.10 on 2026-02-01 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceticket',
            name='source',
            field=models.CharField(choices=[('TENANT', 'Tenant App'), ('ADMIN', 'Property Manager'), ('SYSTEM', 'AI System')], default='ADMIN', max_length=20),
        ),
    ]
