# Generated by Django 5.2.11 on 2026-02-21 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_maintenanceticket_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceticket',
            name='ai_category',
            field=models.CharField(blank=True, choices=[('PLUMBING', 'Plumbing'), ('ELECTRICAL', 'Electrical'), ('HVAC', 'HVAC / Air Conditioning'), ('STRUCTURAL', 'Structural'), ('PEST_CONTROL', 'Pest Control'), ('PAINTING', 'Painting'), ('APPLIANCE', 'Appliance Repair'), ('GENERAL', 'General Maintenance')], default='GENERAL', max_length=20),
        ),
        migrations.AddField(
            model_name='maintenanceticket',
            name='assigned_to',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'MAINTENANCE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenanceticket',
            name='resolution_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
