# Generated by Django 5.2.10 on 2026-01-31 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='is_occupied',
        ),
        migrations.AddField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('RESIDENTIAL', 'Residential'), ('COMMERCIAL', 'Commercial'), ('MIXED', 'Mixed Use')], default='RESIDENTIAL', max_length=20),
        ),
        migrations.AddField(
            model_name='unit',
            name='bathrooms',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='unit',
            name='bedrooms',
            field=models.IntegerField(default=1, help_text='For residential units'),
        ),
        migrations.AddField(
            model_name='unit',
            name='square_feet',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='status',
            field=models.CharField(choices=[('VACANT', 'Vacant'), ('OCCUPIED', 'Occupied'), ('MAINTENANCE', 'Under Maintenance'), ('RESERVED', 'Reserved')], default='VACANT', max_length=20),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit_type',
            field=models.CharField(choices=[('1BHK', '1 Bedroom'), ('2BHK', '2 Bedroom'), ('3BHK', '3 Bedroom'), ('STUDIO', 'Studio'), ('VILLA', 'Villa'), ('OFFICE', 'Office Space'), ('RETAIL', 'Retail Shop'), ('WAREHOUSE', 'Warehouse')], max_length=20),
        ),
    ]
