# Generated by Django 5.2.11 on 2026-02-22 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_remove_unit_is_occupied_property_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='rules_and_regulations',
            field=models.TextField(blank=True, help_text='Building rules, pet policy, parking, gym hours, visitor policy, etc. The AI chatbot uses this to answer tenant questions.', null=True),
        ),
    ]
