# Generated by Django 5.2.10 on 2026-01-28 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=50)),
                ('cheque_number', models.CharField(max_length=20)),
                ('cheque_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending (Safe with Landlord)'), ('DEPOSITED', 'Deposited to Bank'), ('CLEARED', 'Cleared (Money Received)'), ('BOUNCED', 'Bounced (Action Required)')], default='PENDING', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cheques/')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheques', to='core.organization')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheques', to='tenants.tenant')),
            ],
        ),
    ]
