# Generated by Django 5.2.10 on 2026-01-28 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_organization_user_phone_user_role'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheque',
            name='bank_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cheques', to='core.organization'),
        ),
    ]
