# Generated by Django 5.2.10 on 2026-01-28 19:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_cheque_bank_name_alter_cheque_organization'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cheque',
            options={'ordering': ['-cheque_date']},
        ),
        migrations.AddField(
            model_name='cheque',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cheque',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending (Safe with Landlord)'), ('DEPOSITED', 'Deposited to Bank'), ('CLEARED', 'Cleared (Money Received)'), ('BOUNCED', 'Bounced (Action Required)')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
