# Generated by Django 5.2.10 on 2026-02-01 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_cheque_options_cheque_created_at_and_more'),
        ('tenants', '0004_tenant_nationality_alter_tenant_ejari_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheque',
            name='lease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cheques', to='tenants.lease'),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='cheque_number',
            field=models.CharField(max_length=50),
        ),
    ]
