# Generated by Django 5.2.11 on 2026-02-25 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_initial'),
        ('maintenance', '0003_maintenanceticket_ai_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('TICKET_CREATED', 'New Ticket Created'), ('TICKET_ASSIGNED', 'Ticket Assigned to You'), ('TICKET_RESOLVED', 'Ticket Resolved'), ('TICKET_EMERGENCY', 'Emergency Ticket'), ('PAYMENT_DUE', 'Payment Due Soon'), ('LEASE_EXPIRING', 'Lease Expiring'), ('GENERAL', 'General Notice')], default='GENERAL', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='maintenance.maintenanceticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
