# Generated by Django 5.2.11 on 2026-02-26 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0003_notification'),
        ('properties', '0003_property_rules_and_regulations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('TICKET_CREATED', 'New Ticket Created'), ('TICKET_ASSIGNED', 'Ticket Assigned to You'), ('TICKET_RESOLVED', 'Ticket Resolved'), ('TICKET_EMERGENCY', 'Emergency Ticket'), ('INQUIRY', 'New Property Inquiry'), ('TENANT_ONBOARDED', 'New Tenant Onboarded'), ('PAYMENT_DUE', 'Payment Due Soon'), ('LEASE_EXPIRING', 'Lease Expiring'), ('GENERAL', 'General Notice')], default='GENERAL', max_length=30),
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=20)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('ONBOARDED', 'Tenant Onboarded'), ('REJECTED', 'Rejected')], default='NEW', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='properties.property')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='properties.unit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
