# Generated by Django 5.2.10 on 2026-01-28 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='core.organization'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Platform Admin'), ('OWNER', 'Organization Owner'), ('MANAGER', 'Property Manager'), ('FINANCE', 'Finance Officer'), ('AGENT', 'Leasing Agent'), ('MAINTENANCE', 'Maintenance Staff'), ('SECURITY', 'Security Guard'), ('TENANT', 'Tenant')], default='TENANT', max_length=20),
        ),
    ]
