# Generated by Django 5.2.11 on 2026-02-21 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_organization_user_phone_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='specialty',
            field=models.CharField(blank=True, choices=[('PLUMBING', 'Plumbing'), ('ELECTRICAL', 'Electrical'), ('HVAC', 'HVAC / Air Conditioning'), ('STRUCTURAL', 'Structural'), ('PEST_CONTROL', 'Pest Control'), ('PAINTING', 'Painting'), ('APPLIANCE', 'Appliance Repair'), ('GENERAL', 'General Maintenance')], default='GENERAL', max_length=20, null=True),
        ),
    ]
