# Generated by Django 5.2.11 on 2026-02-22 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_specialty'),
        ('properties', '0003_property_rules_and_regulations'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='managed_property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managers', to='properties.property'),
        ),
    ]
